[feat] : 뉴스상세페이지 api 일부 연동 및 api 파일 분리
2024-Fall-CapstoneDesign/newReals_FE pull request #95
Opened 2024-11-29 14:53 UTC by jinaaaaaaaaaaaaa

## #️⃣연관된 이슈

> 연관된 이슈를 작성해주세요.

#87

## 📝작업 내용

> 작업한 내용을 작성해주세요.

- api 파일 분리
- 앞뒤기사 조회 api 연동

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.

2024-11-29 15:47 UTC, yeona813 requested changes
리뷰 천천히 확인해주세요!

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +export const getDetailNews = async (id: number, locationProp: any) => {
any 타입은 지양하는게 조아용 타입을 만들어서 바꿔보는 거 어떨까요?

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +};
let 보단 const를 사용하여 재할당이 안되게 하는게 좋을 것 같아용!
```
try {
  const res = locationProp
    ? await api.get(`/news/${id}`, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
        params: locationProp,
      })
    : await api.get(`/news/${id}`, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });
  return res.data.data;
} catch (error) {
  console.error(error);
}
```

 + return res.data.data를 바로 주지 말고 
```
if (res.data.success) {
 return res.data.data
}
``` 
로 하는거 어떨까요?

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +};
+ res... 난 response로 하기는 하는데 이거 나중에 하나로 통일하긴 하야할 듯 한사람이 한 코드처럼 만드는게 중요할 것 같아서

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +    return res.data.data;
이것도 if로 한번 감싸서 success일 때만 data 넘겨주는거 어떨까요?

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +    return res.data.data;
위와 같은 이유

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +    console.log('응답:', res.data.message);
콘솔 확인 했다면 지워주세용!

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +    return true;
return res.data.success 는 어떨지 ?

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +    return false;
error일 떄 return 값을 주는 이유는 뭘까용?

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +    console.log('응답:', res.data.data);
콘솔 지우기!

2024-11-29 15:47 UTC, yeona813 commented on src/api/NewsDetail.ts
> +  }
위와 동일한 !!!

2024-11-30 11:03 UTC, jinaaaaaaaaaaaaa commented on src/api/NewsDetail.ts
> +    return false;
Insight를 보내고 바로 다시 렌더링되는 작업을 할 때 

const handleClickSendButton = async (input: string) => {
    setIsLoading(true);
    try {
      const isSuccess = await sendInsight(Number(id), input); // 데이터 저장 요청
      if (isSuccess) {
        onCommentUpdated(); // 저장 성공 시 서버 데이터 다시 가져오기
      }
    } catch (error) {
      console.error('오류 발생:', error);
    } finally {
      setIsLoading(false); // 로딩 상태 비활성화
    }
  };

여기서 isSuccess로 판별하려고 false 반환햇습니당 false 반환 없으면 undefined가 된다고 하네염

2024-11-30 11:03 UTC, jinaaaaaaaaaaaaa commented on src/api/NewsDetail.ts
> +  }
이유가 위와 같습니당

2024-11-30 12:20 UTC, yeona813 approved these changes
수고하셨습니다!

2024-12-01 09:24 UTC, merged